# Generated by Django 5.1.15 on 2026-09-09 08:01

import core.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=4, unique=True, validators=[core.validators.validate_business_code], verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Contract Type',
                'verbose_name_plural': 'Contract Types',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=4, unique=True, validators=[core.validators.validate_business_code], verbose_name='Customer Code')),
                ('name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=4, unique=True, validators=[core.validators.validate_business_code], verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Project Status',
                'verbose_name_plural': 'Project Statuses',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=4, unique=True, validators=[core.validators.validate_business_code], verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Project Type',
                'verbose_name_plural': 'Project Types',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=4, unique=True, validators=[core.validators.validate_business_code], verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'TOP',
                'verbose_name_plural': 'TOP',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=4, unique=True, validators=[core.validators.validate_business_code], verbose_name='Vendor Code')),
                ('name', models.CharField(max_length=255, verbose_name='Vendor Name')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_code', models.CharField(max_length=4, unique=True, validators=[core.validators.validate_business_code], verbose_name='Project Code')),
                ('project_name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('contract_start_date', models.DateField(verbose_name='Contract Start')),
                ('contract_end_date', models.DateField(verbose_name='Contract End')),
                ('work_value', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Work Value')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8, verbose_name='Record Status')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.contracttype', verbose_name='Contract Type')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.customer', verbose_name='Customer')),
                ('project_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.projectstatus', verbose_name='Status')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.projecttype', verbose_name='Project Type')),
                ('top', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.top', verbose_name='TOP')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-contract_start_date', 'project_code'],
            },
        ),
    ]
